---
- name: Prepare Debian template with QEMU Guest Agent
  hosts: localhost
  gather_facts: no
  vars:
    template_vm_id: 9000
    proxmox_host: "{{ lookup('env', 'PROXMOX_IP') }}"
    proxmox_node: "{{ lookup('env', 'PROXMOX_NODE') }}"
    ssh_user: "{{ lookup('env', 'CI_USER') }}"
    ssh_priv_key: "~/.ssh/id_rsa"

  tasks:
    - name: Start the template VM
      shell: qm start {{ template_vm_id }}
      delegate_to: localhost

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ template_ip }}"
        port: 22
        timeout: 120
        state: started

    - name: Add temporary host for SSH access
      add_host:
        name: debian-template
        ansible_host: "{{ template_ip }}"
        ansible_user: "{{ ssh_user }}"
        ansible_ssh_private_key_file: "{{ ssh_priv_key }}"

- name: Install QEMU Guest Agent inside template
  hosts: debian-template
  become: true
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes

    - name: Enable and start qemu-guest-agent
      systemd:
        name: qemu-guest-agent
        enabled: true
        state: started

- name: Finalize template and convert back
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Shutdown the template VM
      shell: qm shutdown {{ template_vm_id }} --timeout 60
      delegate_to: localhost

    - name: Enable QEMU Guest Agent in Proxmox hardware config
      shell: qm set {{ template_vm_id }} --agent enabled=1
      delegate_to: localhost

    - name: Convert back to template
      shell: qm template {{ template_vm_id }}
      delegate_to: localhost
