---
- name: Provision Debian VM and configure French locale
  hosts: localhost
  gather_facts: false
  vars:
    vm_id: 120
    vm_name: "debian-vm-auto"
    template_vm_id: "debian-template"
    storage: "HDD-TAFF1"
    target_disk_size: 10G
    proxmox_node: "{{ lookup('env', 'PROXMOX_NODE') }}"
    proxmox_host: "{{ lookup('env', 'PROXMOX_IP') }}"
    api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
    api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
    ci_user: "{{ lookup('env', 'CI_USER') }}"
    ci_pass: "{{ lookup('env', 'CI_PASS') }}"
    ssh_pub_key: "{{ lookup('env', 'SSH_PUB_KEY') }}"

  tasks:
    - name: Clone Debian VM from template
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vm_id }}"
        name: "{{ vm_name }}"
        memory: 1024
        cores: 1
        scsihw: virtio-scsi-single
        ide:
          ide0: 'local:cloudinit,format=qcow2'
        net:
          net0: 'virtio,bridge=vmbr0'
        scsi:
          scsi0: "{{ storage }}:{{ target_disk_size }},format=qcow2"
        agent: 1
        ciuser: "{{ ci_user }}"
        cipassword: "{{ ci_pass }}"
        sshkeys: "{{ ssh_pub_key }}"
        timeout: 60
        state: present

    - name: Wait for VM to get an IP from Guest Agent
      shell: |
        for i in {1..20}; do
          ip=$(qm guest cmd {{ vm_id }} network-get-interfaces | \
               jq -r '.[]."ip-addresses"[]?.["ip-address"]' | \
               grep -v '^127\.' | grep -E '^192\.168|^10\.|^172\.' | head -n1)
          if [ -n "$ip" ]; then echo $ip && break; fi
          sleep 10
        done
      register: vm_ip_result
      changed_when: false
      delegate_to: localhost
      
    - name: Debug detected VM IP
      debug:
        msg: "Detected IP: {{ vm_ip_result.stdout }}"
