---
- name: Create Debian VM on Proxmox with API token
  hosts: localhost
  gather_facts: no
  vars:
    proxmox_node: "proxmox"
    vm_id: 120
    vm_name: "debian-vm-auto"
    template_vm_id: 9000
    storage: "local-lvm"
    target_disk_size: 10G
    proxmox_host: "{{ lookup('env', 'PROXMOX_IP') }}"
    api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
    api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
    api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
    ssh_pub_key: "{{ lookup('env', 'SSH_PUB_KEY') }}"
    ci_user: "{{ lookup('env', 'CI_USER') }}"
    ci_pass: "{{ lookup('env', 'CI_PASS') }}"

  tasks:
    - name: Clone from Debian cloud-init template
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_id | int }}"
        clone: "{{ template_vm_id | int }}"
        name: "{{ vm_name }}"
        storage: "{{ storage }}"
        memory: 1024
        cores: 1
        net:
        net0: virtio,bridge=vmbr0
        ide:
          ide2: "{{ storage }}:cloudinit,media=cdrom"
        sata:
          sata0: "{{ storage }}:{{ target_disk_size }}"
        serial:
          serial0: socket
        ciuser: "{{ ci_user }}"
        cipassword: "{{ ci_pass }}"
        sshkeys: "{{ ssh_pub_key }}"
        state: started
        timeout: 60
        force: true
