---
- name: Create Debian VM on Proxmox with API token
  hosts: localhost
  gather_facts: no
  vars:
    proxmox_node: "{{ lookup('env', 'PROXMOX_NODE') }}"
    vm_id: 120
    vm_name: "debian-vm-auto"
    template_vm_id: "debian-template"
    storage: "HDD-TAFF1"
    target_disk_size: 10G
    proxmox_host: "{{ lookup('env', 'PROXMOX_IP') }}"
    api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
    api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
    api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
    api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
    ssh_pub_key: "{{ lookup('env', 'SSH_PUB_KEY') }}"
    ci_user: "{{ lookup('env', 'CI_USER') }}"
    ci_pass: "{{ lookup('env', 'CI_PASS') }}"
    

  tasks:
    - name: Clone from Debian cloud-init template
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        # api_token_id: "{{ api_token_id }}"
        # api_token_secret: "{{ api_token_secret }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vm_id }}"
        name: "{{ vm_name }}"
        memory: 1024
        cores: 1
        ide:
          ide0: 'local:cloudinit,format=qcow2'
        net:
          net0: 'virtio,bridge=vmbr0'
        scsi:
          scsi0: 'HDD-TAFF1:10,format=raw'
        scsihw: virtio-scsi-single
        ciuser: "{{ ci_user }}"
        cipassword: "{{ ci_pass }}"
        sshkeys: "{{ ssh_pub_key }}"
        timeout: 60
        state: present
        user_data: |
          locale: fr_FR.UTF-8
          keyboard:
            layout: fr
          timezone: Europe/Paris
          packages:
            - locales
          runcmd:
            - locale-gen fr_FR.UTF-8
            - update-locale LANG=fr_FR.UTF-8
